import { useState, type SubmitEventHandler } from "react";

import { Container } from "../Container/Container";

import { ButtonInput } from "../ButtonInput/ButtonInput";
import { Notification } from "../Notification/Notification";

import styles from "./GuessNumber.module.scss";

export const GuessNumber = function () {
	const [message, setMessage] = useState("");
	const [isError, setIsError] = useState(false);
	const [computerNumber, setComputerNumber] = useState(0);

	const generateComputerNumber = function () {
		setComputerNumber(Math.floor(Math.random() * 10));
	};

	const handleSubmit = (value: string) => {
		const intValue = parseInt(value);

		generateComputerNumber();

		setIsError(computerNumber !== intValue);
		setMessage(computerNumber === intValue ? `You guessed the number! (${computerNumber})` : `You didn't guess the number (${computerNumber})`);
	};

	return (
		<>
			<section className={styles["guess-number"]}>
				<Container>
					<h2 className={styles["guess-number__title"]}>Guess the number generated by the computer</h2>
					<div className={styles["guess-number__wrapper"]}>
						<ButtonInput type="number" placeholder="Enter number" onSubmit={handleSubmit} />
						<Notification type="right" status={isError ? "wrong" : "right"}>
							{message}
						</Notification>
					</div>
				</Container>
			</section>
		</>
	);
};
